### ISSUE TITLE
it keeps doing this error

### ISSUE THREAD

**Issue by narmundolegal** [CrimsonSunrise/Blaze-Double-Automator#1]
Traceback (most recent call last):
  File "D:\Downloads\Blaze-Double-Automator-master\Blaze-Double-Automator-master\Blaze Double\main.py", line 13, in <module>
    bot.Bet(bets=[{"color": "red", "amount": 2}], return_results=False)
  File "D:\Downloads\Blaze-Double-Automator-master\Blaze-Double-Automator-master\Blaze Double\Automation.py", line 171, in Bet
    INPUT_AMOUNT.send_keys(str(bet[1]))
KeyError: 1

**Comment by CrimsonSunrise** [comment]
Hello @narmundolegal, hope you're doing fine.

I would love to know more about the problem you are facing.
Did you change any code inside the `Automation.py` file?
And using `headless=False` on the Start method, did you see any weird behavior?
Did error always happened or its situational? For example, it only occurs when you change something?
There's more information on the terminal that you can share?

**Comment by CrimsonSunrise** [comment]
Just found out whats the problem is and pushed a new update.
You can fix by yourself changing the line 171 of the `Automation.py` file from:
`INPUT_AMOUNT.send_keys(str(bet[1]))`
to
`INPUT_AMOUNT.send_keys(str(bet['amount']))`

This will fix the problem you have.
If it didn't solve, feel free to reopen this issue.
