### ISSUE TITLE
find_elements_by_class_name

### ISSUE THREAD

**Issue by jvcunha777** [CrimsonSunrise/Blaze-Double-Automator#6]
Error [False, AttributeError("'WebDriver' object has no attribute 'find_elements_by_class_name'")]
'WebDriver' object has no attribute 'find_elements_by_class_name'
Bot is stopping
Bot stopped

**Comment by CrimsonSunrise** [comment]
Hey @jvcunha777 
Guess you're using a different version of Selenium but a easy workaround for this particular problem, specially because it's something that should be padronized before, so pardon me, is the following:
instead of using:
`while len(driver.find_elements_by_class_name("description")) == 0:`
you should change to:
`while len(driver.find_elements(By.CLASS_NAME, "description")) == 0:`

This change must make it work again.
Let me know if it works for you.

**Comment by jvcunha777** [comment]
How do I place my betting strategy? example: after the number 2 enters red and white

**Comment by CrimsonSunrise** [comment]
As I mentioned on [this issue](https://github.com/CrimsonSunrise/Blaze-Automator/issues/5), you have to listen for the latest results and determine if you want to place a bet after a specific number or color.
This can be done simply by using an `if` statement.
If you don't know how to, I suggest reading [this article](https://www.w3schools.com/python/python_conditions.asp) so you'll have an idea.

The way that the `Automator.py` script was written, you can place a bet right after finding your desireable number or color. The algorithm will wait for the next betting window to place your bet.
